# ================================
# docker-compose.yml - Docker Setup
version: '3.8'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - HF_MODEL=${HF_MODEL}
      - DEBUG=${DEBUG}
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
    volumes:
      - ./:/app
      - ./data:/app/data
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped